# Generated by Django 5.2.5 on 2025-08-31 08:03

import apps.core.models.reservation
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tail_number', models.CharField(max_length=20, unique=True)),
                ('model', models.CharField(max_length=20)),
                ('capacity', models.PositiveIntegerField()),
                ('production_year', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['tail_number'],
                'indexes': [models.Index(fields=['tail_number'], name='core_airpla_tail_nu_ee75f1_idx'), models.Index(fields=['model'], name='core_airpla_model_1b88bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('flight_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('departure', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.airplane')),
            ],
            options={
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_code', models.CharField(db_index=True, default=apps.core.models.reservation.generate_reservation_code, max_length=40, unique=True)),
                ('passenger_name', models.CharField(db_index=True, max_length=40)),
                ('passenger_email', models.CharField(db_index=True, max_length=40)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.flight')),
            ],
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['flight_number'], name='core_flight_flight__161aa9_idx'),
        ),
    ]
